version: '2'
services:
  app:
    container_name: app
    image: 'app'
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - "mysql"
  mysql:
    container_name: app_db
    ports:
      - "33060:3306"
    image: "mysql:5.7.31"
    volumes:
      - ./docker/app.cnf:/etc/mysql/conf.d/app.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
