version: '3'
services:
  app:
    container_name: app
    image: 'app'
    ports:
      - "8080:8080"
    environment:
      - USE_RDS=true
      - RDS_USERNAME=root
      - RDS_PASSWORD=root
      - RDS_HOSTNAME=app_db
      - RDS_PORT=3306
      - RDS_DB_NAME=app
      - APP_NAME=newapp
      - REDIS_ENDPOINT=redis_db
      - ENVIRONMENT_TYPE=development
      - RABBITMQ_ADDRESS=rabbitmq
      - RABBITMQ_USERNAME=root
      - RABBITMQ_USER_PASSWORD=root
      - RABBITMQ_PORT=5672
    env_file:
      - ./.env
    depends_on:
      - "mysql"
      - "redis"
      - "rabbitmq"
  mysql:
    container_name: app_db
    ports:
      - "33060:3306"
    image: "mysql:5.7.31"
    volumes:
      - ./docker/app.cnf:/etc/mysql/conf.d/app.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
  wiremock:
    container_name: app_mock
    ports:
      - "8089:8089"
    image: "rodolpheche/wiremock"
    command: --port 8089
  redis:
    container_name: redis_db
    ports:
      - "6379:6379"
    image: "redis:4.0.9-alpine"
  rabbitmq:
    container_name: app_rabbit
    image: "rabbitmq:3.7.5-management"
    ports:
      - "5672:5672"
      - "8088:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: "root"
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_VHOST: "/"
